export const ADD_RECIPE = "ADD_RECIPE";
export const REMOVE_RECIPE = "REMOVE_RECIPE";
export const OPEN_RECIPE = "OPEN_RECIPE";
export const UPDATE_CURRENT_INDEX = "UPDATE_CURRENT_INDEX";
export const UPDATE_COLLECTION = "UPDATE_COLLECTION";
